[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chronos-api"
version = "0.1.0"
description = "Flask REST API for Chronos Scheduler"
dependencies = [
  "flask",
  "flask-swagger-ui",
  "pydantic",
  "chronos-lib @ file://../chronos-lib"
]
