openapi: 3.1.0
info:
  title: Chronos Scheduler API
  version: "v1"
  description: |
    API for scheduling and querying cron-style jobs.
servers:
  - url: /

paths:
  /jobs:
    post:
      summary: Schedule one or more new jobs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                job_requests:
                  type: array
                  description: A list of jobs to schedule
                  items:
                    $ref: '#/components/schemas/JobRequest'
              required:
                - job_requests
      responses:
        '201':
          description: Jobs scheduled successfully
          content:
            application/json:
              schema:
                type: array
                description: The scheduled jobs
                items:
                  $ref: '#/components/schemas/JobResponse'
    get:
      summary: List all scheduled jobs
      responses:
        '200':
          description: A list of all jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobResponse'

  /jobs/{job_id}:
    get:
      summary: Get a single job by its ID
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
          description: The UUID of the job
      responses:
        '200':
          description: Job details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobResponse'
        '404':
          description: Job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    JobRequest:
      type: object
      properties:
        job_name:
          type: string
          description: A human-readable name for the job
        schedule:
          type: string
          description: Cron expression (e.g. "*/5 * * * *") or interval (e.g. "every:60")
        priority:
          type: integer
          description: Job priority (1=highest, 10=lowest)
          default: 5
        retries:
          type: integer
          description: Number of retry attempts on failure
          default: 3
      required:
        - job_name
        - schedule

    JobResponse:
      type: object
      properties:
        job_id:
          type: string
          description: The UUID assigned to the job
        job_name:
          type: string
          description: The name given at creation
        schedule:
          type: string
          description: The job’s schedule string
        priority:
          type: integer
        retries:
          type: integer
        status:
          type: string
          description: Current job status (PENDING, RUNNING, SUCCESS, FAILED)

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
